//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTanent.DataModel.Datamodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mytanentEntities : DbContext
    {
        public mytanentEntities()
            : base("name=mytanentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCity> tblCities { get; set; }
        public DbSet<tblRoom> tblRooms { get; set; }
        public DbSet<tblState> tblStates { get; set; }
        public DbSet<tblTanentDocument> tblTanentDocuments { get; set; }
        public DbSet<tblTanentRentDetail> tblTanentRentDetails { get; set; }
        public DbSet<tblTanentRoomsDetail> tblTanentRoomsDetails { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblUserBankDetail> tblUserBankDetails { get; set; }
    }
}
