//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTanent.DataModel.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoom
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
