//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTanent.DataModel.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public int id { get; set; }
        public string StateName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
