//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTanent.DataModel.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTanentRoomsDetail
    {
        public System.Guid Id { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<System.Guid> TanentId { get; set; }
        public string SecurityRentPaidAmount { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
