//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTanent.DataModel.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserBankDetail
    {
        public System.Guid Id { get; set; }
        public string BankName { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
