//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTanent.DataModel.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblRooms = new HashSet<tblRoom>();
            this.tblTanentDocuments = new HashSet<tblTanentDocument>();
            this.tblTanentRentDetails = new HashSet<tblTanentRentDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string EmailId { get; set; }
        public string UserId { get; set; }
        public string password { get; set; }
        public string UserType { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Locality { get; set; }
        public string PermanentAddress { get; set; }
        public string UserPhoto { get; set; }
        public string AllotedRoomNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string AllotedFloorNo { get; set; }
    
        public virtual ICollection<tblRoom> tblRooms { get; set; }
        public virtual ICollection<tblTanentDocument> tblTanentDocuments { get; set; }
        public virtual ICollection<tblTanentRentDetail> tblTanentRentDetails { get; set; }
        public virtual tblTanentRoomsDetail tblTanentRoomsDetail { get; set; }
        public virtual tblUserBankDetail tblUserBankDetail { get; set; }
    }
}
